dbt_jobs_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST') }}"
      user: "{{ env_var('DBT_DB_USER') }}"
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      port: "{{ env_var('DBT_DB_PORT') | int }}"
      dbname: "{{ env_var('DBT_DB_NAME') }}"
      schema: public
      threads: 1